name: Deploy WASM to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Select Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Build
        run: wasm-pack build --target web
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - run: wasm-pack test --headless --firefox
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
